package lab

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"slices"
	"time"
)

// Paths of the minted public certs, shared by every consumer in the package
// (the kind mount, the in-cluster secrets, the manifest checksum inputs).
const (
	caCertPath      = "certs/ca.crt"
	tlsCertPath     = "certs/tls.crt"
	gatewayCertPath = "certs/gateway-tls.crt"
	gatewayKeyPath  = "certs/gateway-tls.key"
)

// PEM block types.
const (
	pemTypeCert = "CERTIFICATE"
	pemTypeKey  = "PRIVATE KEY"
)

// GenCerts mints a self-signed CA and a Dex server certificate under certs/.
// The server cert carries both IP:127.0.0.1 and DNS:localhost in its SAN — the
// issuer URL uses the *name* (muster rejects issuers whose host parses as a
// loopback IP; a name that merely resolves to one passes).
// Existing certs are left alone unless force is set: regenerating invalidates
// the CA baked into the running cluster's apiserver flags.
func GenCerts(force bool) error {
	if err := os.MkdirAll("certs", 0o750); err != nil {
		return err
	}
	if _, err := os.Stat(filepath.Join("certs", "tls.crt")); err == nil && !force {
		// Tighten keys generated by older versions of the lab (they were 644).
		for _, k := range []string{"ca.key", "tls.key"} {
			_ = os.Chmod(filepath.Join("certs", k), 0o600)
		}
		fmt.Println("certs/ already populated (agentlab certs --force to regenerate)")
		return nil
	}

	caKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return err
	}
	caTmpl := &x509.Certificate{
		SerialNumber:          randomSerial(),
		Subject:               pkix.Name{CommonName: "agentlab-ca"},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().AddDate(0, 0, 3650),
		IsCA:                  true,
		BasicConstraintsValid: true,
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
	}
	caDER, err := x509.CreateCertificate(rand.Reader, caTmpl, caTmpl, &caKey.PublicKey, caKey)
	if err != nil {
		return err
	}

	srvKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return err
	}
	srvTmpl := &x509.Certificate{
		SerialNumber: randomSerial(),
		Subject:      pkix.Name{CommonName: componentDex},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().AddDate(0, 0, 3650),
		KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		IPAddresses:  []net.IP{net.ParseIP("127.0.0.1")},
		DNSNames:     []string{"localhost", componentDex, "dex.dex.svc", "dex.dex.svc.cluster.local"},
	}
	caCert, err := x509.ParseCertificate(caDER)
	if err != nil {
		return err
	}
	srvDER, err := x509.CreateCertificate(rand.Reader, srvTmpl, caCert, &srvKey.PublicKey, caKey)
	if err != nil {
		return err
	}

	// Certs are public, keys are not: nothing in the lab needs world-readable
	// keys (the kind mount only reads ca.crt in-node).
	writes := []struct {
		path string
		pem  *pem.Block
		mode os.FileMode
	}{
		{caCertPath, &pem.Block{Type: pemTypeCert, Bytes: caDER}, 0o644},
		{"certs/ca.key", &pem.Block{Type: pemTypeKey, Bytes: mustPKCS8(caKey)}, 0o600},
		{tlsCertPath, &pem.Block{Type: pemTypeCert, Bytes: srvDER}, 0o644},
		{"certs/tls.key", &pem.Block{Type: pemTypeKey, Bytes: mustPKCS8(srvKey)}, 0o600},
	}
	for _, w := range writes {
		if err := os.WriteFile(w.path, pem.EncodeToMemory(w.pem), w.mode); err != nil {
			return err
		}
	}
	fmt.Println("Generated certs/ (CA + server cert, SAN: IP:127.0.0.1, DNS:localhost, dex, dex.dex.svc, dex.dex.svc.cluster.local)")
	return nil
}

// ensureGatewayCert mints the wildcard certificate the agentgateway edge
// terminates TLS with (*.<domain> plus the apex), signed by the existing lab
// CA so every consumer that already trusts certs/ca.crt (the lab tooling,
// muster, Backstage via NODE_EXTRA_CA_CERTS) trusts the edge too. Existing
// files are kept while they still cover the configured domain; a domain
// change re-mints them from the same CA.
func ensureGatewayCert(domain string) error {
	wildcard := "*." + domain
	if raw, err := os.ReadFile(gatewayCertPath); err == nil { // #nosec G304 -- lab-owned path constant
		if block, _ := pem.Decode(raw); block != nil {
			if cert, err := x509.ParseCertificate(block.Bytes); err == nil &&
				slices.Contains(cert.DNSNames, wildcard) {
				return nil
			}
		}
	}
	caCert, caKey, err := loadCA()
	if err != nil {
		return err
	}
	srvKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return err
	}
	tmpl := &x509.Certificate{
		SerialNumber: randomSerial(),
		Subject:      pkix.Name{CommonName: wildcard},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().AddDate(0, 0, 3650),
		KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		DNSNames:     []string{wildcard, domain},
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, caCert, &srvKey.PublicKey, caKey)
	if err != nil {
		return err
	}
	certPEM := pem.EncodeToMemory(&pem.Block{Type: pemTypeCert, Bytes: der})
	if err := os.WriteFile(gatewayCertPath, certPEM, 0o644); err != nil { // #nosec G306 -- certificates are public
		return err
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: pemTypeKey, Bytes: mustPKCS8(srvKey)})
	if err := os.WriteFile(gatewayKeyPath, keyPEM, 0o600); err != nil {
		return err
	}
	fmt.Printf("Generated %s (SAN: %s, %s; signed by the lab CA)\n", gatewayCertPath, wildcard, domain)
	return nil
}

// loadCA reads the lab CA pair minted by GenCerts.
func loadCA() (*x509.Certificate, *rsa.PrivateKey, error) {
	certPEM, err := os.ReadFile(caCertPath)
	if err != nil {
		return nil, nil, fmt.Errorf("reading lab CA (run `agentlab certs` first?): %w", err)
	}
	block, _ := pem.Decode(certPEM)
	if block == nil {
		return nil, nil, fmt.Errorf("%s contains no PEM certificate", caCertPath)
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, nil, err
	}
	keyPEM, err := os.ReadFile("certs/ca.key")
	if err != nil {
		return nil, nil, err
	}
	block, _ = pem.Decode(keyPEM)
	if block == nil {
		return nil, nil, fmt.Errorf("certs/ca.key contains no PEM key")
	}
	parsed, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return nil, nil, err
	}
	key, ok := parsed.(*rsa.PrivateKey)
	if !ok {
		return nil, nil, fmt.Errorf("certs/ca.key is not an RSA key")
	}
	return cert, key, nil
}

func mustPKCS8(key *rsa.PrivateKey) []byte {
	der, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		panic(err)
	}
	return der
}

func randomSerial() *big.Int {
	max := new(big.Int).Lsh(big.NewInt(1), 128)
	n, err := rand.Int(rand.Reader, max)
	if err != nil {
		panic(err)
	}
	return n
}
