package lab

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"time"

	"github.com/giantswarm/agentlab/internal/config"
	"github.com/giantswarm/agentlab/internal/labs"
)

// Paths of the minted certs, shared by every consumer in the package
// (the kind mount, the in-cluster secrets, the manifest checksum inputs).
const (
	caCertPath      = "certs/ca.crt"
	caKeyPath       = "certs/ca.key"
	tlsCertPath     = "certs/tls.crt"
	tlsKeyPath      = "certs/tls.key"
	gatewayCertPath = "certs/gateway-tls.crt"
	gatewayKeyPath  = "certs/gateway-tls.key"
	// trustBundlePath is what the lab's consumers trust with an externally
	// provisioned pair (platform.tls): the lab CA plus the pair's chain,
	// which Dex and the edge then serve (writeIssuerFiles).
	trustBundlePath = "certs/trust-bundle.crt"
	// apiserverHostsPath is the kube-apiserver's /etc/hosts with an
	// externally provisioned pair: dex.<domain> on loopback, where the Dex
	// NodePort answers (kind-config.yaml.tmpl).
	apiserverHostsPath = "certs/apiserver-hosts"
	// replacedCADir stashes CAs that a re-mint replaced: the trust stores
	// index roots by name+serial, so removing one later needs the very
	// certificate that was installed. `agentlab trust`/`untrust` sweep this
	// dir out of the stores and delete it (see sweepReplacedCAs).
	replacedCADir = "certs/replaced"
)

// PEM block types.
const (
	pemTypeCert = "CERTIFICATE"
	pemTypeKey  = "PRIVATE KEY"
)

// The CA lives ten years; leafs are capped at 825 days because Apple
// platforms (macOS 10.15+/iOS 13+, HT210176) reject TLS server certs valid
// any longer — regardless of the root being user-trusted — so a longer leaf
// is a red lock on macOS even after `agentlab trust`. Leafs re-mint from
// the unchanged CA (no re-trust needed) inside the renewal window.
const (
	caValidityDays   = 3650
	leafValidityDays = 825
	leafRenewWindow  = 30 * 24 * time.Hour
)

// dexSANNames are the DNS names of the Dex server cert: the issuer name
// (localhost — see docs/identity.md on why not 127.0.0.1) plus the in-cluster
// service names. Also the fixed half of the CA's name constraints.
var dexSANNames = []string{localhostName, componentDex, "dex.dex.svc", "dex.dex.svc.cluster.local"}

// permittedDNSNames is the CA's DNS name-constraint allowlist: the platform
// domain plus the fixed lab names. Everything a lab leaf will ever carry,
// and nothing else.
func permittedDNSNames(domain string) []string {
	names := append([]string{domain}, dexSANNames...)
	slices.Sort(names)
	return slices.Compact(names)
}

// constrainedDomain returns the platform domain a CA's name constraints pin
// (the one entry that is not a fixed lab name), or "" when there is none.
func constrainedDomain(ca *x509.Certificate) string {
	for _, name := range ca.PermittedDNSDomains {
		if !slices.Contains(dexSANNames, name) {
			return name
		}
	}
	return ""
}

// GenCerts mints the lab CA and the Dex server certificate under certs/.
// Existing files are kept while they match the configuration and policy;
// only what must change is re-minted, and `--force` re-mints everything.
//
// The CA carries X.509 name constraints — permitted DNS subtrees for the
// platform domain, localhost and the Dex in-cluster names, permitted IP
// range 127.0.0.0/8 — so once `agentlab trust` installs it, a leaked CA key
// still cannot sign for the web at large. Non-critical for old-verifier
// compatibility; Go, OpenSSL, Chrome, Firefox and macOS enforce them
// regardless. The constraints pin the domain, so a platform.domain change
// re-mints the CA: the trust step must be repeated, and a running cluster's
// apiserver keeps the replaced CA until the cluster is recreated.
//
// The Dex server cert carries both IP:127.0.0.1 and DNS:localhost in its
// SAN — the issuer URL uses the *name* (muster rejects issuers whose host
// parses as a loopback IP; a name that merely resolves to one passes).
func GenCerts(domain string, force bool) error {
	if err := os.MkdirAll("certs", 0o750); err != nil {
		return err
	}
	// Tighten keys generated by older versions of the lab (they were 644).
	for _, k := range []string{caKeyPath, tlsKeyPath, gatewayKeyPath} {
		_ = os.Chmod(k, 0o600)
	}

	caCert := readCertFile(caCertPath)
	caReason := ""
	switch {
	case caCert == nil:
		if _, err := os.Stat(caCertPath); err == nil {
			caReason = "the existing CA is unreadable"
		}
	case force:
		caReason = "agentlab certs --force"
	case !slices.Contains(caCert.PermittedDNSDomains, domain):
		if old := constrainedDomain(caCert); old != "" {
			caReason = fmt.Sprintf("platform.domain is now %q, the CA's name constraints pin %q", domain, old)
		} else {
			caReason = "the existing CA predates name constraints"
		}
	}

	if caCert == nil || caReason != "" {
		if caReason != "" {
			fmt.Printf("Re-minting the lab CA: %s.\n", caReason)
			fmt.Println("  - trust must be re-established: run `agentlab trust` again (it also removes the")
			fmt.Println("    replaced CA from the trust stores), or restart NODE_EXTRA_CA_CERTS consumers")
			fmt.Println("  - a running cluster's apiserver still pins the replaced CA: agentlab down && agentlab up")
		}
		if caCert != nil {
			if err := stashReplacedCA(caCert); err != nil {
				return err
			}
		}
		var err error
		if caCert, err = mintCA(domain); err != nil {
			return err
		}
		fmt.Printf("Generated %s (%d-day CA; name constraints: DNS %s, IP 127.0.0.0/8)\n",
			caCertPath, caValidityDays, strings.Join(permittedDNSNames(domain), ", "))
	}

	leafReason := leafRemintReason(readCertFile(tlsCertPath), caCert, dexSANNames)
	if force && leafReason == "" {
		leafReason = "agentlab certs --force"
	}
	if leafReason == "" {
		fmt.Println("certs/ already populated (agentlab certs --force to regenerate)")
		return nil
	}
	_, caKey, err := loadCA()
	if err != nil {
		return err
	}
	if err := mintLeaf(caCert, caKey, componentDex, dexSANNames,
		[]net.IP{net.ParseIP("127.0.0.1")}, tlsCertPath, tlsKeyPath); err != nil {
		return err
	}
	fmt.Printf("Generated %s (%s; %d-day leaf, SAN: IP:127.0.0.1, DNS:%s)\n",
		tlsCertPath, leafReason, leafValidityDays, strings.Join(dexSANNames, ","))
	return nil
}

// trustBundleFile is the CA bundle every consumer of the lab trusts (the
// dex-ca Secrets, the apiserver's OIDC CA, Substrate's egress, the lab's own
// clients): the lab CA, or with an externally provisioned pair the bundle
// writeIssuerFiles adds its chain to.
func trustBundleFile(cfg *config.Config) string {
	if cfg.Platform.TLS.Set() {
		return trustBundlePath
	}
	return caCertPath
}

// writeIssuerFiles writes what the issuer under the platform domain needs
// with an externally provisioned pair (platform.tls): the trust bundle —
// the lab CA plus every certificate of the pair's cert file, so a private
// or self-signed pair verifies wherever the lab CA did, and a public one
// where only the lab CA is trusted (the apiserver's oidc-ca-file replaces
// the system roots) — and the apiserver's hosts file. Without a pair there
// is nothing to write.
func writeIssuerFiles(cfg *config.Config) error {
	if !cfg.Platform.TLS.Set() {
		return nil
	}
	ca, err := os.ReadFile(caCertPath)
	if err != nil {
		return fmt.Errorf("reading lab CA (run `agentlab certs` first?): %w", err)
	}
	chain, err := pemCertificates(cfg.Platform.TLS.CertFile)
	if err != nil {
		return err
	}
	if err := os.WriteFile(trustBundlePath, append(ca, chain...), 0o644); err != nil { // #nosec G306 G703 -- public certificates, to a lab-owned path constant
		return err
	}
	hosts := fmt.Sprintf("127.0.0.1 localhost %s\n::1 localhost\n", cfg.DexHost())
	return os.WriteFile(apiserverHostsPath, []byte(hosts), 0o644) // #nosec G306 -- read in the node like ca.crt
}

// dexServingPair is the certificate pair Dex serves: the lab-CA leaf for
// localhost, or the externally provisioned pair its issuer then lives
// under (config.Issuer).
func dexServingPair(cfg *config.Config) (cert, key string) {
	if cfg.Platform.TLS.Set() {
		return cfg.Platform.TLS.CertFile, cfg.Platform.TLS.KeyFile
	}
	return tlsCertPath, tlsKeyPath
}

// pemCertificates returns the CERTIFICATE blocks of a PEM file, re-encoded,
// so a bundle never carries anything else the file holds.
func pemCertificates(path string) ([]byte, error) {
	raw, err := os.ReadFile(path) // #nosec G304 -- the configured platform.tls.certFile
	if err != nil {
		return nil, err
	}
	var out []byte
	for block, rest := pem.Decode(raw); block != nil; block, rest = pem.Decode(rest) {
		if block.Type == pemTypeCert {
			out = append(out, pem.EncodeToMemory(block)...)
		}
	}
	if out == nil {
		return nil, fmt.Errorf("%s holds no PEM certificate", path)
	}
	return out, nil
}

// ensureGatewayCert mints the wildcard certificate the agentgateway edge
// terminates TLS with (*.<domain> plus the apex), signed by the lab CA so
// every consumer that trusts certs/ca.crt (the lab tooling, muster,
// Backstage, the system store after `agentlab trust`) trusts the edge too.
// Existing files are kept while they cover the configured domain, chain to
// the current CA and sit inside leaf policy; anything else re-mints from
// the same CA — no re-trust needed.
func ensureGatewayCert(domain string) error {
	caCert, caKey, err := loadCA()
	if err != nil {
		return err
	}
	wildcard := "*." + domain
	dns := []string{wildcard, domain}
	if cert := readCertFile(gatewayCertPath); cert != nil && leafRemintReason(cert, caCert, dns) == "" {
		return nil
	}
	if err := mintLeaf(caCert, caKey, wildcard, dns, nil, gatewayCertPath, gatewayKeyPath); err != nil {
		return err
	}
	fmt.Printf("Generated %s (SAN: %s, %s; signed by the lab CA, %d-day leaf)\n",
		gatewayCertPath, wildcard, domain, leafValidityDays)
	return nil
}

// leafRemintReason says why an existing leaf must be re-minted from the
// current CA, or "" to keep it. Covers the CA rotating underneath it (a
// --force or domain change), expiry, missing SAN entries, and leafs that
// older labs minted with 3650-day validity — which Apple platforms reject
// even under a trusted root.
func leafRemintReason(cert, ca *x509.Certificate, wantDNS []string) string {
	switch {
	case cert == nil:
		return "minting"
	case cert.CheckSignatureFrom(ca) != nil:
		return "signed by a replaced CA"
	case time.Until(cert.NotAfter) < leafRenewWindow:
		return "expiring"
	case cert.NotAfter.Sub(cert.NotBefore) > (leafValidityDays+1)*24*time.Hour:
		return "validity exceeded Apple's 825-day cap"
	}
	for _, name := range wantDNS {
		if !slices.Contains(cert.DNSNames, name) {
			return "SAN missing " + name
		}
	}
	return ""
}

// mintCA writes a fresh name-constrained lab CA pair and returns the cert.
func mintCA(domain string) (*x509.Certificate, error) {
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return nil, err
	}
	_, loopback, err := net.ParseCIDR("127.0.0.0/8")
	if err != nil {
		return nil, err
	}
	tmpl := &x509.Certificate{
		SerialNumber:          randomSerial(),
		Subject:               pkix.Name{CommonName: "agentlab-ca"},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().AddDate(0, 0, caValidityDays),
		IsCA:                  true,
		BasicConstraintsValid: true,
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
		// Only lab names — non-critical so verifiers that predate name
		// constraints still accept the chain; the ones that matter enforce
		// them regardless.
		PermittedDNSDomainsCritical: false,
		PermittedDNSDomains:         permittedDNSNames(domain),
		PermittedIPRanges:           []*net.IPNet{loopback},
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		return nil, err
	}
	if err := writePEM(caCertPath, pemTypeCert, der, 0o644); err != nil {
		return nil, err
	}
	if err := writePEM(caKeyPath, pemTypeKey, mustPKCS8(key), 0o600); err != nil {
		return nil, err
	}
	return x509.ParseCertificate(der)
}

// mintLeaf signs a server certificate with the lab CA. Leaf validity is
// capped at leafValidityDays (Apple's limit); the CA outlives its leafs, so
// re-minting one changes no trust anchors.
func mintLeaf(caCert *x509.Certificate, caKey *rsa.PrivateKey, cn string, dns []string, ips []net.IP, certPath, keyPath string) error {
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return err
	}
	tmpl := &x509.Certificate{
		SerialNumber: randomSerial(),
		Subject:      pkix.Name{CommonName: cn},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().AddDate(0, 0, leafValidityDays),
		KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		DNSNames:     dns,
		IPAddresses:  ips,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, caCert, &key.PublicKey, caKey)
	if err != nil {
		return err
	}
	if err := writePEM(certPath, pemTypeCert, der, 0o644); err != nil {
		return err
	}
	return writePEM(keyPath, pemTypeKey, mustPKCS8(key), 0o600)
}

// stashReplacedCA keeps a copy of a CA that is about to be overwritten, so
// a later trust operation can still remove it from the trust stores.
func stashReplacedCA(cert *x509.Certificate) error {
	if err := os.MkdirAll(replacedCADir, 0o750); err != nil {
		return err
	}
	path := filepath.Join(replacedCADir, cert.SerialNumber.String()+".crt")
	return writePEM(path, pemTypeCert, cert.Raw, 0o644)
}

// writePEM writes one PEM block. Certs are public (0644 — the kind mount
// reads ca.crt in-node), keys are 0600.
func writePEM(path, blockType string, der []byte, mode os.FileMode) error {
	return os.WriteFile(path, pem.EncodeToMemory(&pem.Block{Type: blockType, Bytes: der}), mode) // #nosec G306 -- 0644 only for public certificates
}

// readCertFile parses the first PEM certificate in path; nil when the file
// is missing or does not parse (callers mint a fresh one then).
func readCertFile(path string) *x509.Certificate {
	raw, err := os.ReadFile(path) // #nosec G304 -- lab-owned path constants
	if err != nil {
		return nil
	}
	block, _ := pem.Decode(raw)
	if block == nil {
		return nil
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil
	}
	return cert
}

// absCAPath is the CA path for copy-pasteable env exports.
func absCAPath() string {
	abs, err := filepath.Abs(caCertPath)
	if err != nil {
		return caCertPath
	}
	return abs
}

// loadCA reads the lab CA pair minted by GenCerts.
func loadCA() (*x509.Certificate, *rsa.PrivateKey, error) {
	certPEM, err := os.ReadFile(caCertPath)
	if err != nil {
		return nil, nil, fmt.Errorf("reading lab CA (run `agentlab certs` first?): %w", err)
	}
	block, _ := pem.Decode(certPEM)
	if block == nil {
		return nil, nil, fmt.Errorf("%s contains no PEM certificate", caCertPath)
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, nil, err
	}
	keyPEM, err := os.ReadFile(caKeyPath)
	if err != nil {
		return nil, nil, err
	}
	block, _ = pem.Decode(keyPEM)
	if block == nil {
		return nil, nil, fmt.Errorf("%s contains no PEM key", caKeyPath)
	}
	parsed, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return nil, nil, err
	}
	key, ok := parsed.(*rsa.PrivateKey)
	if !ok {
		return nil, nil, fmt.Errorf("%s is not an RSA key", caKeyPath)
	}
	return cert, key, nil
}

func mustPKCS8(key *rsa.PrivateKey) []byte {
	der, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		panic(err)
	}
	return der
}

func randomSerial() *big.Int {
	max := new(big.Int).Lsh(big.NewInt(1), 128)
	n, err := rand.Int(rand.Reader, max)
	if err != nil {
		panic(err)
	}
	return n
}

// RequireLabCerts refuses a lab directory that has no certs/ while its
// cluster exists: the cluster was made from certs that live in the lab's own
// directory (the registered one, under the state directory
// ~/.local/state/<lab> for a leased lab), so a checkout whose agentlab.yaml
// merely names that clusterName reports the lab and then fails on the first
// certificate it reads. The refusal names the lab's directory and --lab.
func RequireLabCerts(cfg *config.Config) error {
	if _, err := os.Stat(caCertPath); err == nil {
		return nil
	}
	switch labClusterState(cfg.ClusterName) {
	case "not created", "unknown":
		return nil // a lab not up yet mints its certs on `up`; docker silent: its own errors follow
	}
	here, _ := os.Getwd()
	dir := "~/.local/state/" + cfg.ClusterName
	if registered, err := labs.List(); err == nil {
		for _, l := range registered {
			if l.Name == cfg.ClusterName && l.Dir != here {
				dir = l.Dir
			}
		}
	}
	return fmt.Errorf("the kind cluster %q exists, but %s has no %s: the lab's certificates are in its own lab directory, %s — run the command there or with `--lab %s`",
		cfg.ClusterName, here, caCertPath, dir, cfg.ClusterName)
}
