package lab

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"time"
)

// GenCerts mints a self-signed CA and a Dex server certificate under certs/.
// The server cert carries both IP:127.0.0.1 and DNS:localhost in its SAN — the
// issuer URL uses the *name* (muster rejects issuers whose host parses as a
// loopback IP; a name that merely resolves to one passes).
// Existing certs are left alone unless force is set: regenerating invalidates
// the CA baked into the running cluster's apiserver flags.
func GenCerts(force bool) error {
	if err := os.MkdirAll("certs", 0o755); err != nil {
		return err
	}
	if _, err := os.Stat(filepath.Join("certs", "tls.crt")); err == nil && !force {
		// Tighten keys generated by older versions of the lab (they were 644).
		for _, k := range []string{"ca.key", "tls.key"} {
			_ = os.Chmod(filepath.Join("certs", k), 0o600)
		}
		fmt.Println("certs/ already populated (agentlab certs --force to regenerate)")
		return nil
	}

	caKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return err
	}
	caTmpl := &x509.Certificate{
		SerialNumber:          randomSerial(),
		Subject:               pkix.Name{CommonName: "dex-lab-ca"},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().AddDate(0, 0, 3650),
		IsCA:                  true,
		BasicConstraintsValid: true,
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
	}
	caDER, err := x509.CreateCertificate(rand.Reader, caTmpl, caTmpl, &caKey.PublicKey, caKey)
	if err != nil {
		return err
	}

	srvKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return err
	}
	srvTmpl := &x509.Certificate{
		SerialNumber: randomSerial(),
		Subject:      pkix.Name{CommonName: "dex"},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().AddDate(0, 0, 3650),
		KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		IPAddresses:  []net.IP{net.ParseIP("127.0.0.1")},
		DNSNames:     []string{"localhost", "dex", "dex.dex.svc", "dex.dex.svc.cluster.local"},
	}
	caCert, err := x509.ParseCertificate(caDER)
	if err != nil {
		return err
	}
	srvDER, err := x509.CreateCertificate(rand.Reader, srvTmpl, caCert, &srvKey.PublicKey, caKey)
	if err != nil {
		return err
	}

	// Certs are public, keys are not: nothing in the lab needs world-readable
	// keys (the kind mount only reads ca.crt in-node).
	writes := []struct {
		path string
		pem  *pem.Block
		mode os.FileMode
	}{
		{"certs/ca.crt", &pem.Block{Type: "CERTIFICATE", Bytes: caDER}, 0o644},
		{"certs/ca.key", &pem.Block{Type: "PRIVATE KEY", Bytes: mustPKCS8(caKey)}, 0o600},
		{"certs/tls.crt", &pem.Block{Type: "CERTIFICATE", Bytes: srvDER}, 0o644},
		{"certs/tls.key", &pem.Block{Type: "PRIVATE KEY", Bytes: mustPKCS8(srvKey)}, 0o600},
	}
	for _, w := range writes {
		if err := os.WriteFile(w.path, pem.EncodeToMemory(w.pem), w.mode); err != nil {
			return err
		}
	}
	fmt.Println("Generated certs/ (CA + server cert, SAN: IP:127.0.0.1, DNS:localhost, dex, dex.dex.svc, dex.dex.svc.cluster.local)")
	return nil
}

func mustPKCS8(key *rsa.PrivateKey) []byte {
	der, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		panic(err)
	}
	return der
}

func randomSerial() *big.Int {
	max := new(big.Int).Lsh(big.NewInt(1), 128)
	n, err := rand.Int(rand.Reader, max)
	if err != nil {
		panic(err)
	}
	return n
}
