package lab

import (
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/giantswarm/agentlab/internal/config"
)

// The observability stack is not part of the umbrella chart's BOM, so the lab
// pins its two charts itself, flux.go-style (Go consts, bumped deliberately).
//
// kube-prometheus-stack is the Giant Swarm wrapper chart — the exact
// constituent (chart, version, registry, images) the observability-bundle
// pins. The bundle itself cannot run here: it renders Flux HelmReleases wired
// for the MC->WC model (a hardcoded remote kubeconfig secret, dependsOn on
// HelmReleases the lab lacks, Alloy configs generated by
// observability-operator against Mimir) and deliberately ships no local PromQL
// endpoint. The lab installs the constituent directly and re-enables the
// Prometheus server — see kube-prometheus-stack-values.yaml.tmpl.
const (
	kpsChartVersion = "22.0.0" // wraps upstream kube-prometheus-stack 87.3.0
	// 0.8.0: OAuth provider switch and tenancy mode `none` (a single-tenant
	// Prometheus behind muster; the lab's identity proofs need both).
	mcpPrometheusChartVersion = "0.8.0"
)

// observabilityNamespace also appears in the templates (the PROMETHEUS_URL in
// mcp-prometheus-values and the MCPServer URL in agent-platform-values), which
// must stay in agreement.
const observabilityNamespace = "monitoring"

const (
	// kpsRelease is deliberately short: the upstream subchart prefixes every
	// object with the release name (the Prometheus CR becomes
	// kps-kube-prometheus-stack-prometheus as it is).
	kpsRelease           = "kps"
	mcpPrometheusRelease = "mcp-prometheus"
)

// observabilityUp installs the minimal observability stack: the GS
// kube-prometheus-stack (operator + CRDs + kube-state-metrics + node-exporter
// + a Prometheus scraping kubelet/cAdvisor) and mcp-prometheus, the MCP server
// muster registers via the umbrella's agent-platform-mcps values (see
// agent-platform-values.yaml.tmpl) and forwards the user's Dex id_token to.
// Runs BEFORE the umbrella install so muster's first dial of the MCPServer CR
// finds a listener.
func observabilityUp(cfg *config.Config) error {
	step("Installing the observability stack (kube-prometheus-stack %s + mcp-prometheus %s)",
		kpsChartVersion, mcpPrometheusChartVersion)
	if err := installOCIChart(cfg, kpsRelease,
		"oci://gsoci.azurecr.io/charts/giantswarm/kube-prometheus-stack",
		kpsChartVersion, "kube-prometheus-stack-values.yaml.tmpl", false); err != nil {
		return err
	}
	// mcp-prometheus runs as an OAuth resource server against the lab Dex
	// (mcp-prometheus-values.yaml.tmpl): it needs the lab CA in its own
	// namespace to verify Dex's certificate, so the Secret muster and
	// Backstage use in agent-platform is mirrored here before the install.
	if err := ensureNamespace(observabilityNamespace); err != nil {
		return err
	}
	if err := ensureSecretFromFiles(observabilityNamespace, "dex-ca", map[string]string{
		"ca.crt": caCertPath,
	}); err != nil {
		return err
	}
	// Through the lab post-renderer: mcp-prometheus gets the dex-localhost
	// sidecar that makes the issuer URL (https://localhost:<DexPort>)
	// reachable from inside the pod (postrender.go, item 4).
	if res := sideloadImages(cfg, hostPullImages([]string{dexLocalhostImage})); res.n > 0 {
		note("side-loaded the dex-localhost sidecar image (%s)", res.d)
	}
	if err := installOCIChart(cfg, mcpPrometheusRelease,
		"oci://gsoci.azurecr.io/charts/giantswarm/mcp-prometheus",
		mcpPrometheusChartVersion, "mcp-prometheus-values.yaml.tmpl", true); err != nil {
		return err
	}

	// helm --wait returns as soon as kstatus is happy, but the operator creates
	// the Prometheus StatefulSet asynchronously after the CR lands — so "helm
	// succeeded" does not mean a query endpoint exists yet. Wait for the CR to
	// report an available replica; without it the mcp-prometheus tools connect
	// fine and then fail every query.
	step("Waiting for Prometheus to serve (the operator creates it after the install)")
	replicas := ""
	up := waitFor(40, 3*time.Second, func() bool {
		// Fully qualified on principle (same reason as mcpservers): other
		// charts may ship colliding kinds.
		replicas, _ = outputQuiet("kubectl", "-n", observabilityNamespace,
			"get", "prometheuses.monitoring.coreos.com",
			"-o", "jsonpath={.items[0].status.availableReplicas}")
		n, err := strconv.Atoi(strings.TrimSpace(replicas))
		return err == nil && n >= 1
	})
	if !up {
		return fmt.Errorf("no available Prometheus replica after the install (last status: %q);\n"+
			"check `kubectl -n %s get prometheus,statefulset,pods`",
			replicas, observabilityNamespace)
	}
	note("Prometheus is serving (PromQL inside the cluster: http://prometheus-operated.%s:9090)",
		observabilityNamespace)

	// The edge route Backstage's Mimir integration queries
	// (observability-route.yaml.tmpl); paired with the mimirEnabled override
	// in backstage-catalog.yaml.tmpl. Applied regardless of Backstage so the
	// endpoint is also there for humans and platform-test.
	if _, routePath, err := renderManifest(cfg, "observability-route.yaml.tmpl"); err != nil {
		return err
	} else if err := runQuiet("kubectl", "apply", "-f", routePath); err != nil {
		return err
	}
	note("PromQL on the edge: %s/api/v1/query (what Backstage's Deployments/Clusters metrics use)",
		cfg.ObservabilityBaseURL())
	return nil
}

// installOCIChart renders the values template and installs one pinned OCI
// chart into the observability namespace, side-loading its images first (the
// same host-cache -> node rule as the platform; see flux.go for the pattern
// and preload.go for the rule).
// postRender routes the release through the lab post-renderer (PostRender).
func installOCIChart(cfg *config.Config, release, chartRef, version, valuesTmpl string, postRender bool) error {
	_, valuesPath, err := renderManifest(cfg, valuesTmpl)
	if err != nil {
		return err
	}
	// Best-effort, like flux.go: anything missed is pulled in-node under the
	// --wait timeout, and the snapshot manifest catches it for the next boot.
	if rendered, err := outputQuiet("helm", "template", release, chartRef,
		"--version", version,
		"-n", observabilityNamespace, "-f", valuesPath); err == nil {
		if imgs := scrapeImages(rendered); len(imgs) > 0 {
			if res := sideloadImages(cfg, hostPullImages(imgs)); res.n > 0 {
				note("side-loaded %d %s images (%s)", res.n, release, res.d)
			}
		}
	}
	args := []string{"upgrade", "--install", release, chartRef,
		"--version", version,
		"-n", observabilityNamespace, "--create-namespace",
		"-f", valuesPath,
		"--wait", "--timeout", "5m"}
	if !postRender {
		return runQuiet("helm", args...)
	}
	pluginsDir, err := ensurePostRenderPlugin()
	if err != nil {
		return err
	}
	args = append(args, "--post-renderer", postRenderPluginName)
	return runQuietEnv([]string{"HELM_PLUGINS=" + pluginsDir}, "helm", args...)
}
