package lab

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	"github.com/giantswarm/agentlab/internal/config"
)

// The observability stack is not part of the agent-platform chart, so the lab
// pins its two charts itself (Go consts, bumped deliberately).
//
// kube-prometheus-stack is the Giant Swarm wrapper chart — the exact
// constituent (chart, version, registry, images) the observability-bundle
// pins. The bundle itself cannot run here: it renders Flux HelmReleases wired
// for the MC->WC model (a hardcoded remote kubeconfig secret, dependsOn on
// HelmReleases the lab lacks, Alloy configs generated by
// observability-operator against Mimir) and deliberately ships no local PromQL
// endpoint. The lab installs the constituent directly and re-enables the
// Prometheus server — see kube-prometheus-stack-values.yaml.tmpl.
const (
	kpsChartVersion = "22.0.0" // wraps upstream kube-prometheus-stack 87.3.0
	// 0.8.0: OAuth provider switch and tenancy mode `none` (a single-tenant
	// Prometheus behind muster; the lab's identity proofs need both). An exact
	// version: the OCIRepository's semver range is this pin.
	mcpPrometheusChartVersion = "0.8.0"
)

// observabilityNamespace also appears in the templates (the PROMETHEUS_URL and
// targetNamespace in mcp-prometheus.yaml.tmpl, the MCPServer URL in
// agent-platform-values), which must stay in agreement.
const observabilityNamespace = "monitoring"

const (
	// kpsRelease is deliberately short: the upstream subchart prefixes every
	// object with the release name (the Prometheus CR becomes
	// kps-kube-prometheus-stack-prometheus as it is).
	kpsRelease           = "kps"
	mcpPrometheusRelease = "mcp-prometheus"
)

// prometheusResource is the operator's Prometheus CR as kubectl's resource
// argument — fully qualified on principle (same reason as mcpservers): other
// charts may ship colliding kinds.
const prometheusResource = "prometheuses.monitoring.coreos.com"

// observabilityUp installs the lab Prometheus: the GS kube-prometheus-stack
// (operator + CRDs + kube-state-metrics + node-exporter + a Prometheus
// scraping kubelet/cAdvisor) and the edge route Backstage queries it through.
// Runs BEFORE the platform chart on purpose: the chart's cluster-shape knobs
// detect monitoring.coreos.com/v1 once, at render time, and the components'
// ServiceMonitors need the operator. The MCP server for it (mcp-prometheus)
// follows the platform — see mcpPrometheusUp.
func observabilityUp(cfg *config.Config) error {
	ctx := context.Background()
	step("Installing the observability stack (kube-prometheus-stack %s)", kpsChartVersion)
	if err := installOCIChart(cfg, kpsRelease,
		"oci://gsoci.azurecr.io/charts/giantswarm/kube-prometheus-stack",
		kpsChartVersion, "kube-prometheus-stack-values.yaml.tmpl"); err != nil {
		return err
	}
	// mcp-prometheus runs as an OAuth resource server against the lab Dex
	// (mcp-prometheus.yaml.tmpl): it needs the lab CA in its own namespace to
	// verify Dex's certificate, so the Secret muster and Backstage use in
	// agent-platform is mirrored here.
	if err := ensureNamespace(observabilityNamespace); err != nil {
		return err
	}
	if err := ensureSecretFromFiles(observabilityNamespace, "dex-ca", map[string]string{
		caCertKey: caCertPath,
	}); err != nil {
		return err
	}

	// Helm's wait returns as soon as kstatus is happy, but the operator creates
	// the Prometheus StatefulSet asynchronously after the CR lands — so "the
	// install succeeded" does not mean a query endpoint exists yet. Wait for the CR to
	// report an available replica; without it the mcp-prometheus tools connect
	// fine and then fail every query.
	step("Waiting for Prometheus to serve (the operator creates it after the install)")
	var replicas string
	var readErr error
	up := waitFor(40, 3*time.Second, func() bool {
		replicas, readErr = prometheusAvailableReplicas(ctx)
		n, err := strconv.Atoi(replicas)
		return readErr == nil && err == nil && n >= 1
	})
	if !up {
		return notReached("the Prometheus CR", "an available replica after the install", replicas, readErr,
			fmt.Sprintf("check `kubectl -n %s get prometheus,statefulset,pods`", observabilityNamespace))
	}
	note("Prometheus is serving (PromQL inside the cluster: http://prometheus-operated.%s:9090)",
		observabilityNamespace)

	// The edge route Backstage's Mimir integration queries
	// (observability-route.yaml.tmpl); paired with the mimirEnabled override
	// in backstage-catalog.yaml.tmpl. Applied regardless of Backstage so the
	// endpoint is also there for humans and platform-test.
	if route, _, err := renderManifest(cfg, "observability-route.yaml.tmpl"); err != nil {
		return err
	} else if _, err := applyManifests(ctx, route); err != nil {
		return err
	}
	note("PromQL on the edge: %s/api/v1/query (what Backstage's Deployments/Clusters metrics use)",
		cfg.ObservabilityBaseURL())
	return nil
}

// prometheusAvailableReplicas is `{.items[0].status.availableReplicas}` of
// the Prometheus CRs in the observability namespace: "" while the operator
// has not reported any, an error when there is no CR — or no CRD — to read.
func prometheusAvailableReplicas(ctx context.Context) (string, error) {
	gvr, err := gvrFor(prometheusResource)
	if err != nil {
		return "", err
	}
	items, err := listObjects(ctx, gvr, observabilityNamespace, "")
	if err != nil {
		return "", err
	}
	if len(items) == 0 {
		return "", fmt.Errorf("no %s in %s yet", prometheusResource, observabilityNamespace)
	}
	n, found, err := unstructured.NestedInt64(items[0].Object, "status", "availableReplicas")
	if err != nil || !found {
		return "", nil
	}
	return strconv.FormatInt(n, 10), nil
}

// mcpPrometheusTemplate renders the lab's mcp-prometheus release: a Flux
// OCIRepository + HelmRelease in the platform namespace, installed into the
// observability namespace by the platform's bundled helm-controller as the
// tenant identity the chart renders (agent-platform-flux).
const mcpPrometheusTemplate = "mcp-prometheus.yaml.tmpl"

// mcpPrometheusUp registers the Prometheus MCP server with the engine: the
// lab's one release outside the meta chart rides the same helm-controller, so
// its lab-only dex-localhost sidecar is a postRenderers patch like the
// platform components' (postrenderers.go) — no post-renderer binary, no
// second Helm writer. muster registers the server through the platform's
// agent-platform-mcps values (agent-platform-values.yaml.tmpl) and forwards
// the user's Dex id_token to it. Runs after the platform install: the Flux
// CRDs and the tenant ServiceAccount come with the chart.
func mcpPrometheusUp(cfg *config.Config) error {
	step("Installing mcp-prometheus %s through the platform's engine", mcpPrometheusChartVersion)
	manifest, _, err := renderManifest(cfg, mcpPrometheusTemplate)
	if err != nil {
		return err
	}
	if _, err := applyManifests(context.Background(), manifest); err != nil {
		return err
	}
	var status platformReleaseStatus
	var readErr error
	ready := waitFor(60, 5*time.Second, func() bool {
		var releases []platformReleaseStatus
		releases, readErr = platformReleases()
		if readErr != nil {
			return false
		}
		for _, r := range releases {
			if r.name == mcpPrometheusRelease {
				status = r
				return r.ready == conditionTrue
			}
		}
		return false
	})
	if !ready {
		// The Ready condition's message is the controller's own account of
		// why (a failed chart pull, a timed-out install): part of the last
		// status, not a failure of the read.
		last := status.ready
		if status.message != "" {
			last += " (" + status.message + ")"
		}
		return notReached("HelmRelease "+mcpPrometheusRelease, conditionReady, last, readErr,
			fmt.Sprintf("check `kubectl -n %s describe helmrelease %s` and `kubectl -n %s get pods`", platformNamespace, mcpPrometheusRelease, observabilityNamespace))
	}
	return nil
}

// ociChartInstallTimeout bounds the observability chart's upgrade-or-install
// and its wait.
const ociChartInstallTimeout = 5 * time.Minute

// installOCIChart renders the values template and installs one pinned OCI
// chart into the observability namespace through the embedded Helm (an
// idempotent upgrade-or-install with the kstatus wait, creating the namespace),
// side-loading its images first (the same host-cache -> node rule as the
// platform; see preload.go).
func installOCIChart(cfg *config.Config, release, chartRef, version, valuesTmpl string) error {
	_, valuesPath, err := renderManifest(cfg, valuesTmpl)
	if err != nil {
		return err
	}
	values, err := helmValuesFile(valuesPath)
	if err != nil {
		return err
	}
	// Best-effort: anything missed is pulled in-node under the wait timeout,
	// and the snapshot manifest catches it for the next boot.
	if rendered, err := helmTemplate(observabilityNamespace, release, chartRef, version, values, nil); err == nil {
		if imgs := scrapeImages(rendered); len(imgs) > 0 {
			if res := sideloadImages(cfg, hostPullImages(imgs)); res.n > 0 {
				note("side-loaded %d %s images (%s)", res.n, release, res.d)
			}
		}
	}
	return helmUpgradeInstall(observabilityNamespace, release, chartRef, version, values, ociChartInstallTimeout, helmInstallOptions{CreateNamespace: true})
}
